#! /usr/bin/env python3
import say
import bot
from time import sleep
from html.parser import HTMLParser

SLEEP_TIME = 2


class Bot:
    def __init__(self, sessionid, token, last_uuid, functions, read_from_anon=False):
        self.sessionid = sessionid
        self.token = token
        self.last_uuid = last_uuid
        if not last_uuid:
            if read_from_anon:
                self.last_uuid = bot.get_last_uuid(None, None)
            else:
                self.last_uuid = bot.get_last_uuid(self.token, self.sessionid)

        self.functions = functions
        self.ignore = []
        self.HTMLParser = HTMLParser()
        self.read_from_anon = read_from_anon

    def run(self):
        current_uuid = self.last_uuid

        while True:
            print("[read thread] try to grab messages")
            if self.read_from_anon:
                posts = bot.get_last_messages(current_uuid, None, None)
            else:
                posts = bot.get_last_messages(current_uuid, self.token,
                                              self.sessionid)
            print("[read thread] done")

            if len(posts['messages']) > 0:
                current_uuid = posts['messages'][-1][0]

            for uuid, time, name, msg in posts['messages']:
                msg = self.HTMLParser.unescape(msg)
                if msg in self.ignore:
                    self.ignore.remove(msg)
                    print("[write thread] skipped")
                    continue
                for func in self.functions:
                    buff = func(uuid, time, name, msg)
                    if bool(buff):
                        for msg in buff:
                            say.send_message(msg, self.token,
                                             sessionid=self.sessionid)
                            self.ignore.append(msg)

            print("[read thread] sleep")
            sleep(SLEEP_TIME)
            print("[read thread] done")
