#! /usr/bin/env python3
import botbase
import getrandom
from sys import argv
from prepare_arguments import get_argument, get_bool_argument
from uuid import uuid1
from random import randint, choice

token = None
sessionid = False

last_uuid = get_argument(argv, '--uuid')
sessionid = get_argument(argv, '--sessionid')
token = get_argument(argv, '--token')
read_from_anon = get_bool_argument(argv, '--anon-read')

usage = ("Usage: lurkabot --uuid (uuid) --token [token]"
         "--sessionid (sessionid) [--anon-read]")
if (not token) or get_bool_argument(argv, '--help'):
    print(usage)
    exit(1)

censored = ["хуй", "пизда", "залупа", "жобе", "петух"]
copypaste_file = "/home/kasper/src/txt/copypaste/lurka1/lurka1"
antifaggot = "%s – %s – не матерись, хули ты '%s' сказал-то (%s) -> %s"


def filter_word(uuid, time, name, msg):
    result = []
    for word in msg.split(' '):
        if word in censored:
            print("[write thread] faggot")
            random_petuh = censored[randint(0, len(censored) - 1)]
            result.append(antifaggot % (name, random_petuh,
                                        word, time, uuid1()))
    return result


def get_pasta(uuid, time, name, msg):
    if "дай пасты" in msg:
        print("[write thread] pasta request")
        return [getrandom.get_random_from_file(copypaste_file)]


def generate_chain(src):
    src = src.split()
    src = list(map(lambda c: c[:-1] if c[-1] == "," else c,
                   src))
    dest = {}
    src = ["*START*"] + src + ["*END*"]

    for i in range(0, len(src) - 1):
        word = src[i]
        if word != "*END*":
            next = src[i + 1]
            if word in dest:
                dest[word].append(next)
            else:
                dest[word] = [next]

    return dest


def add_dict_with_list(a, b):
    buff = a.copy()
    for elem in b:
        if elem in buff:
            buff[elem] += b[elem]
        else:
            buff[elem] = b[elem]

    return buff


fin = open("delusional.txt", 'r')
text = fin.read()
fin.close()

text = text.replace("?", ".")
text = text.replace("!", ".")
text = text.split(". ")
deutsch = {}
for addition in text:
    deutsch = add_dict_with_list(deutsch, generate_chain(addition))


def not_alice(uuid, time, name, msg):
    if (name == "Alice") or ("бред" in msg):
        print("[write thread] Alice detected")
        msg = ""
        current_word = "*START*"
        while current_word != "*END*":
            current_word = choice(deutsch[current_word])
            if current_word != "*END*":
                msg += current_word + " "

        return [(msg + " -> %s") % (uuid1())]


functions = [filter_word, get_pasta, not_alice]
bot = botbase.Bot(sessionid, token, last_uuid,
                  functions, read_from_anon=read_from_anon)
bot.run()
