#! /usr/bin/env python3
import botbase
import getrandom
from sys import argv
from prepare_arguments import get_argument, get_bool_argument
from uuid import uuid1
from random import randint

token = "bot"
sessionid = False

last_uuid = get_argument(argv, '--uuid')
sessionid = get_argument(argv, '--sessionid')
token = get_argument(argv, '--token')

usage = "Usage: lurkabot --uuid (uuid) --token [token] --sessionid (sessionid)"
if (not token) or get_bool_argument(argv, '--help'):
    print(usage)
    exit(1)

censored = ["хуй", "пизда", "залупа", "жобе", "петух"]
copypaste_file = "/home/kasper/src/txt/copypaste/lurka1/lurka1"
antifaggot = "%s – %s – не матерись, хули ты '%s' сказал-то (%s) -> %s"


def filter_word(uuid, time, name, msg):
    result = []
    for word in msg.split(' '):
        if word in censored:
            print("[write thread] faggot")
            random_petuh = censored[randint(0, len(censored) - 1)]
            result.append(antifaggot % (name, random_petuh,
                                        word, time, uuid1()))
    return result


def get_pasta(uuid, time, name, msg):
    if "дай пасты" in msg:
        print("[write thread] pasta request")
        return [getrandom.get_random_from_file(copypaste_file)]


alice_gut = ["Kinder, Küche, Kirche! -> %s",
             "I habe dich, Alice. -> %s",
             "Ja, ja. -> %s",
             "Ich habe drei Schweinen. -> %s",
             "Meine Ehre Heißt Treue! -> %s"]


def not_alice(uuid, time, name, msg):
    if name == "Alice":
        print("[write thread] Alice detected")
        random_alice = alice_gut[randint(0, len(alice_gut) - 1)]
        return [random_alice % (uuid1())]


functions = [filter_word, get_pasta, not_alice]
bot = botbase.Bot(sessionid, token, last_uuid, functions)
bot.run()
