#! /usr/bin/env python3
import botbase
import getrandom
from sys import argv
from prepare_arguments import get_argument

token = "bot"
sessionid = False

last_uuid = get_argument(argv, '--uuid')
sessionid = get_argument(argv, '--sessionid')
token = get_argument(argv, '--token')

if (not token) or get_bool_argument(argv, '--help'):
    print("Usage: lurkabot --uuid (uuid) --token [token] --sessionid (sessionid)")
    exit(1)

censored = ["хуй", "пизда", "ебля", "залупа", "жобе", "петух"]
copypaste_file = "/home/kasper/src/txt/copypaste/lurka1/lurka1"

def filter_word(uuid, time, name, msg):
    result = []
    for word in msg.split(' '):
        if word in censored:
            print("faggot")
            result.append("%s, пидорас, не матерись, хули ты '%s' сказал-то (%s)" % (name, word, time))
    return result

def get_pasta(uuid, time, name, msg):
    if "дай пасты" in msg:
        print("pasta request")
        return [getrandom.get_random_from_file(copypaste_file)]

functions = [filter_word, get_pasta]
bot = botbase.Bot(sessionid, token, last_uuid, functions)
bot.run()

