#! /usr/bin/env python3
# -*- coding: utf-8 -*-
from sys import argv, exit, stdin
from uuid import uuid1
from constants import *
from prepare_arguments import get_bool_argument, get_argument
import requests

place = "/chat/%s/message" % room

def send_message(msg, token, sessionid=False):
    data = {"csrfmiddlewaretoken": token, \
            "message": msg}

    headers = {"Conetent-type": "application/x-www-form-urlencoded", \
               "Accept": "text/plain", \
               "Referer": "https://beta.mlug.ru/chat/tsmr"}

    jar = requests.cookies.RequestsCookieJar()
    jar.set("csrftoken", token, domain="beta.mlug.ru", path="/")
    if sessionid != False:
        jar.set("sessionid", sessionid, domain="beta.mlug.ru", path="/")

    return requests.post(dest + place, data=data, headers=headers, cookies=jar)

if __name__ == "__main__":
    without_uuid = get_bool_argument(argv, '--without-uuid')
    print_request = get_bool_argument(argv, '--print-request')
    sessionid = get_argument(argv, '--sessionid')
    token = get_argument(argv, '--token')

    if not token or get_bool_argument(argv, '--help'):
        print('say --token [token] --sessionid (sessionid) [--without-uuid] [--print-request]')
        exit(1)

    message = stdin.read()

    if not without_uuid:
        msg = "%s :: %s" % (message, str(uuid1()))
    else:
        msg = message

    req = send_message(msg, token, sessionid=sessionid)
    if print_request:
        print(req.text)

